Bugfix reparameterize
sandialabs/pyGSTi pull request #480
Opened 2024-08-23 18:12 UTC by juangmendoza19

Addressing issue #425. 

convert() function has been changed for POVM elements and state preparation. They now support proper conversion from full TP to GLND parameterization. The optimization is now done over non-gauge directions, which are found through Jacobians.

This function still needs to be changed to appropriately handle other reparameterizations.

Lastly, this is not guaranteed to work for POVMs, just because the number of degrees of freedom of a POVM can be greater than the number of error generators that span TP maps for a given number of qubits. By pigeon hole principle, we may not be able to find a description for a POVM consisting of Ideal_POVM + error generators. There is an assertion to try to catch this.

2024-09-19 18:10 UTC, sserita reviewed
Just bookkeeping: Not ready for review, rerequest from me when ready.

2025-02-20 23:24 UTC, juangmendoza19 commented on pygsti/baseobjs/errorgenbasis.py
> +
Fancy code below to find the index of a label was not working for 2 qubits. Temporary easy solution implemented by just calling index(). This was creating problems during the creation of 2 qubit FOGI models

2025-02-20 23:27 UTC, juangmendoza19 commented on pygsti/modelmembers/povms/__init__.py
> +                                base_items.append((lbl, convert_effect(vec, 'static', basis, idl.get(lbl, None), flatten_structure)))
This is code to properly collect the ideal POVM effects. Before, the ideal_effect passed in was being ignored

2025-02-20 23:31 UTC, juangmendoza19 commented on pygsti/modelmembers/povms/__init__.py
> +
Code added to find errgen parameterization for POVMs based on optimization, just like state prep was being done before, but for some reason was never implemented on POVMs. Note that the optimization variations are done over a POVM space that lacks the dumb-gauge/metagauge. To find that space we wrote the function calc_physical_subspace which does a numerical calculation of the Jacobian with respect to POVM parameters.

2025-02-20 23:37 UTC, juangmendoza19 commented on pygsti/modelmembers/states/__init__.py
> +                    #we only vary physical directions, not independent error generators
Just as explained in the POVM init file, we added a function to identify the dumb-gauge/metagauge and move orthogonally to it. This allows for better optimization.

2025-02-20 23:38 UTC, juangmendoza19 commented on pygsti/modelmembers/states/__init__.py
> +                                         tol=1e-13)  # , callback=callback)
the objective function to be optimized over was modified to work with linear combinations of error generators which lack these dumb-gauge degrees of freedom

2025-02-20 23:39 UTC, juangmendoza19 commented on pygsti/models/explicitmodel.py
> +                                ideal_model=None, flatten_structure=False, set_default_gauge_group=False, cptp_truncation_tol= 1e-7, spam_cptp_penalty = 1e-6):
added piping for the cptp penalty factor to be used in the optimization within the SPAM convert functions discussed above

2025-02-20 23:40 UTC, juangmendoza19 commented on pygsti/tools/jamiolkowski.py
> +    return sumOfNeg
Created a function to sum the negative choi eigenvalues of a single gate to be used in our optimization functions to measure CPTPness

2025-02-22 17:21 UTC, juangmendoza19 commented
All the code that was changed which does not have a comment attached was a result of merging the develop branch.

2025-02-23 03:07 UTC, coreyostrove commented
The commits coming from merging in develop shouldn't be showing up, so something got glitched out here. I can confirm that when I just went into the new PR creation interface and looked at the diff that was created for merging in this branch into develop only the new commits related to these bugfixes showed up. This might be the sort of thing that fixes itself if you switch the merge target to something other than develop (e.g. master) and then back again. It doesn't look like I have the permissions to do that on my end, so could either @juangmendoza19  or someone else with the requisite permissions give that a shot?

2025-02-23 20:25 UTC, coreyostrove requested changes
See my inline comments and questions below. Thanks!

2025-02-23 20:25 UTC, coreyostrove commented on pygsti/modelmembers/states/__init__.py
> +                        dense_basis = Basis.cast('pp', (2**num_qubits)**2)
This shouldn't assume a hardcoded pauli-product basis. I don't think the error generator modelmember itself has a basis attribute to grab, but it should have a reference to a parent model which would have this available. Can you update this to grab the appropriate basis? (And if you were doing something similar for the POVMs and I missed it add the change there too.)

2025-02-23 20:25 UTC, coreyostrove commented on pygsti/tools/optools.py
Is this the official @rileyjmurray endorsed fix for this? Do we no longer need this check?

2025-02-27 22:52 UTC, sserita requested changes
One refactor requested, and a few minor fixes while you are at it.

2025-02-27 22:52 UTC, sserita commented on test/unit/objects/test_model.py
> +class LinbladModelTester(GLNDModelBase, StandardMethodBase, BaseCase):
Typo: Linblad -> Lindblad

2025-02-27 22:52 UTC, sserita commented on pygsti/modelmembers/povms/__init__.py
> +    ##TEST CONVERSION BETWEEN LINBLAD TYPES
Remove comment?

2025-02-27 22:53 UTC, sserita requested changes
Forgot to hit Enter on my refactor request...

2025-02-27 22:53 UTC, sserita commented on pygsti/modelmembers/states/__init__.py
> +                                         tol=1e-13)  # , callback=callback)
Is this function exactly the same as the other one (at first glance they at least look very similar)?.
If they are the same (or are the same up to some minor change that could be controlled with a function parameter), can you refactor this function out to avoid code duplication?

2025-04-14 02:35 UTC, coreyostrove commented
@juangmendoza19 and @sserita : Do either of you recall what still needs to get sorted out on this PR? I see that there is at least one merge conflict (probably from merging in develop recently) and some unresolved discussion threads above.

2025-04-14 17:00 UTC, juangmendoza19 commented
> @juangmendoza19 and @sserita : Do either of you recall what still needs to get sorted out on this PR? I see that there is at least one merge conflict (probably from merging in develop recently) and some unresolved discussion threads above.

Stefan’s requests above have not been implemented yet.

2025-05-22 17:10 UTC, coreyostrove commented on pygsti/tools/optools.py
Bump for @rileyjmurray

2025-05-22 17:52 UTC, rileyjmurray commented on pygsti/tools/optools.py
This was the official endorsed fix. It's no longer needed, so I support removing.

2025-05-22 18:41 UTC, rileyjmurray requested changes
Left a few comments. Happy to iterate quickly to see them resolved!

2025-05-22 18:41 UTC, rileyjmurray commented on pygsti/modelmembers/povms/__init__.py
> +def convert(povm, to_type, basis, cp_penalty=1e-7, ideal_povm=None, flatten_structure=False):
When adding keyword arguments it's good to append them to the existing argument sequence. This way if someone uses positional arguments they don't get an error when using updated code. In this situation, placing the new cp_penalty keyword argument before the existing ideal_povm keyword argument could lead to errors for people specifying ideal_povm by its position.

2025-05-22 18:41 UTC, rileyjmurray commented on pygsti/modelmembers/povms/__init__.py
> +                    num_entries = dense_ideal_povm.shape[0]*dense_ideal_povm.shape[1]
If ``dense_ideal_povm`` is a 2d numpy array then it's equivalent to set ``num_entries = dense_ideal_povm.size``.

2025-05-22 18:41 UTC, rileyjmurray commented on pygsti/modelmembers/povms/__init__.py
> +                            vectorized_povm[j*len(perturbed_povm_t[0]):(j+1)*len(perturbed_povm_t[0])] = column
Minimum change: assign ``len(perturbed_povm_t[0])`` to a variable before the for-loop. Then use that variable in the loop for improved readability.

Preferred change: replace the for loop with ``vectorized_povm = perturbed_povm.flatten(order='F')``. Note that you don't need to predefine ``vectorized_povm = _np.zeros(num_entries)`` if you make this change.

2025-05-22 18:41 UTC, rileyjmurray commented on pygsti/modelmembers/povms/__init__.py
> +                        J[:,i] = vectorized_povm.transpose()
You've defined ``vectorized_povm`` as a 1d numpy array. Calling ``.transpose()`` on such an array has no effect.

2025-05-22 18:41 UTC, rileyjmurray commented on pygsti/modelmembers/povms/__init__.py
> +                        new_vec[i] = epsilon
Minor point: rather than defining ``new_vec`` at the start of every loop, you can define it before the loop, then at the start of a loop iteration you set ``new_vec[i] = epsilon`` and at the end of the iteration you set ``new_vec[i] = 0``.

2025-05-22 18:41 UTC, rileyjmurray commented on pygsti/modelmembers/povms/__init__.py
> +                    return V[:len(S),]
Three comments.
1. numpy and scipy SVD functions return the transpose of V, not V itself. So it's good naming convention to say ``Vt`` instead of ``V``. If you were dealing with complex matrices then you'd want to write ``Vh`` instead of ``V``.
2. If you only need the first "number of singular value" singular vectors, then you should call this as ``_, _, Vt = _np.linalg.svd(J, full_matrices=False)``.
3. This implementation isn't checking if any singular values in ``S`` are zero. If they are, then you probably want tor return fewer singular vectors. Consider how, in the current implementation, ``V[:len(S),]`` can be can arbitrary orthogonal matrix when ``J`` is the zero matrix.

2025-05-22 18:41 UTC, rileyjmurray commented on pygsti/modelmembers/states/__init__.py
> +                    errgen_vec = _np.linalg.pinv(phys_directions)  @ soln.x
If you want to apply the pseudo-inverse of a matrix to a vector, it's better to do that implicitly by solving a least squares problem: ``errgen_vec = _np.linalg.lstsq(phys_directions, soln.x)[0]``.

2025-05-22 18:41 UTC, rileyjmurray commented on pygsti/tools/jamiolkowski.py
> +    evals = _np.linalg.eigvals(J)  # could use eigvalsh, but wary of this since eigh can be wrong...
Please elaborate on what you noticed when using ``eigh`` instead of ``eig``. I'd consider the former function more reliable than the latter.

Did you just copy over the comment from ``sums_of_negative_choi_eigenvalues`` which predates this PR?

2025-05-22 18:41 UTC, rileyjmurray commented on test/unit/objects/test_model.py
If you're editing code that uses ``_np.dot``, please go ahead and change to use the infix operator ``@`` instead.

2025-05-22 18:41 UTC, rileyjmurray commented on test/unit/objects/test_model.py
> +    pass
Why is this needed / what is it accomplishing?

2025-05-22 23:42 UTC, coreyostrove commented on pygsti/tools/jamiolkowski.py
> +    evals = _np.linalg.eigvals(J)  # could use eigvalsh, but wary of this since eigh can be wrong...
This one I can confirm is a carry over comment from Erik's original code, but I don't know what he meant by this.

2025-05-22 23:52 UTC, coreyostrove commented on test/unit/objects/test_model.py
> +    pass
The testing code (a lot of which is architected like this) is kind of a pain to read. The way to parse this is that a set of generically defined testing methods (generic in the sense of they make sense independent of a model's parameterization) defined in `StandardMethodBase` should be run against a model with parameterization as defined in `GLNDModelBase`, with access to a number of useful testing utilities defined in `BaseCase`. So while it doesn't look like the class definition does anything, it is actually the case that the act of wrapping all of those parent classes as done here (and with particular keywords in the class name) results in a test suite which pytest knows how to parse and run (I think it looks for "Tester" in the class name, among other possible keywords).

2025-05-23 14:49 UTC, rileyjmurray commented on test/unit/objects/test_model.py
> +    pass
Gotcha. Marking as resolved!

2025-05-23 14:50 UTC, rileyjmurray commented on pygsti/tools/jamiolkowski.py
> +    evals = _np.linalg.eigvals(J)  # could use eigvalsh, but wary of this since eigh can be wrong...
Ping @enielse. Do you remember why you preferred eig as opposed to eigh?

2025-05-24 17:18 UTC, rileyjmurray commented on pygsti/modelmembers/povms/__init__.py
> +                    return V[:len(S),]
@juangmendoza19, can you take a look at points 2 and 3? My sense is that if ``S[i]`` is near zero then you wouldn't want to include ``Vt[i,:]`` among the returned vectors. Ping @coreyostrove in case you can provide insight on how (near-)zero singular values should be handled.

2025-05-24 20:06 UTC, coreyostrove commented on pygsti/modelmembers/povms/__init__.py
> +                    return V[:len(S),]
Your intuition is correct, singular vectors associated with near-zero singular vectors shouldn't be included. It looks like Juan's most recent pair of commits accounts for this now.

2025-05-27 03:44 UTC, rileyjmurray commented on pygsti/modelmembers/povms/__init__.py
> +                    return V[:len(S),]
Just looked at the change. The logic is fine with me now, but I did leave a comment asking that the three or four lines be reduced to a single line.

2025-05-27 04:04 UTC, rileyjmurray commented on pygsti/tools/jamiolkowski.py
> +    evals = _np.linalg.eigvals(J)  # could use eigvalsh, but wary of this since eigh can be wrong...
I opened issue #582 to investigate this. Marking this issue as resolved so we can get this merged.

2025-05-27 04:04 UTC, rileyjmurray approved these changes

2025-05-27 04:15 UTC, coreyostrove commented on test/unit/objects/test_output.txt
This looks like it was accidentally added to one of your commits. Could you delete this?

2025-05-27 04:17 UTC, coreyostrove commented
> @coreyostrove this looks good to me. Other than resolving any merge conflicts or failing tests, do you still have unaddressed comments?
> 
> I see that Stefan has unresolved comments. Rather than try to resolve those I suggest we dismiss Stefan's review (see screenshot below) and make a GitHub issue about following up on Stefan's unresolved points later. <img alt="image" width="855" src="https://private-user-images.githubusercontent.com/10662932/447749267-f610ea24-828a-43b9-869e-f03af8f8d85f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDgzMTk2MTUsIm5iZiI6MTc0ODMxOTMxNSwicGF0aCI6Ii8xMDY2MjkzMi80NDc3NDkyNjctZjYxMGVhMjQtODI4YS00M2I5LTg2OWUtZjAzYWY4ZjhkODVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTI3VDA0MTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMzhiNWQzNzM2NTRmY2E0NGY5MDMzZGVlNzcyMGE5ZTM3YThhMTQxZmZjYzgzZDRjMDJiYzA2NGIwMGZhZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.09LjAuWTWyWGg19dTrRGAA_TPhSaeMFJm13kNY8vhJQ">

One more minor change related to an errant file on my end, but after that I'm satisfied with all of this. I'll approve once that last change is made and we have confirmation that tests are still passing.

2025-05-27 20:46 UTC, rileyjmurray commented
@coreyostrove all tests pass. If you approve then we can merge.

2025-05-29 00:58 UTC, coreyostrove approved these changes
Great work, @juangmendoza19! And thanks for bearing with the many changes requested during the review process.

2025-05-29 00:59 UTC, merged