Simplify the TimeIndependentMDCObjectiveFunction class
sandialabs/pyGSTi pull request #515
Opened 2024-12-16 18:17 UTC by rileyjmurray

TimeIndependentMDCObjectiveFunction is one of the most complicated classes I've encountered in pyGSTi. Right now ...
* It's 1000 lines long.
* It has 12 private instance methods.
* It has hard-to-track dependencies between functions for computing "lsvec-related" quantities and "terms-related" quantities.

This PR simplifies TimeIndependentMDCObjectiveFunction so that
 * It's 668 lines long.
 * It has 4 private instance methods.
 * All "lsvec-related" quantities are computed by applying simple transformations to "terms-related" quantities.

These changes should materially improve maintainability of TimeIndependentMDCObjectiveFunction, as well as its 8 subclasses that collectively span ~500 lines. The outward behavior of this class should be the same as before up to floating point rounding errors.

For the curious, I went down this rabbit hole when working on PR #506.

TODO prior to making this PR as ready for review: review docstrings and correct any inaccuracies.

2024-12-16 20:05 UTC, rileyjmurray commented
Flake8 caught some embarrassing errors:
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/fc81a594-511d-449a-a219-914262b5ef34" />
Will fix.

2024-12-16 23:04 UTC, rileyjmurray commented
I've got a question for you, @enielse. I'm looking at TimeIndependentMDCObjectiveFunction.lsvec:
https://github.com/sandialabs/pyGSTi/blob/5e2465fffa63fbc19c7f061cc2783e10252e949c/pygsti/objectivefns/objectivefns.py#L4755-L4780

The docstring says that an error is raised if the terms vector contains negative values. However, I don't see explicit checks for that.

Intuitively, if we wanted the function's behavior to match the docstring, we should check that ``all(terms >= 0)`` only if  ``oob_check`` was True (skipping the check if ``oob_check`` was False).  Right now, ``oob_check`` is only used once, in a way that's unrelated to the ``terms >= 0`` check, _and_ in a way that'll inadvertently raise an error if the model's forward simulator is anything other than TermForwardSimulator.

https://github.com/sandialabs/pyGSTi/blob/5e2465fffa63fbc19c7f061cc2783e10252e949c/pygsti/objectivefns/objectivefns.py#L4805-L4807

In my refactoring of TimeIndependentMDCObjectiveFunction.lsvec I'm inclined to take the following approach.
```python
    def lsvec(self, paramvec=None, oob_check=False):
        lsvec = self.terms(paramvec, "LS OBJECTIVE")
        if oob_check and _np.any(lsvec < 0):
            bad_locs = _np.where(lsvec < 0)[0]
            msg = f"""
            lsvec is only defined when terms is elementwise nonnegative.
            We encountered negative values for terms[i] for indices i
            in {bad_locs}.
            """
            raise RuntimeError(msg)
        lsvec **= 0.5
        return lsvec
```
What do you think of this? There are two things going on.
1. This function's behavior with TermForwardSimulator would be meaningfully different (we're no longer calling ``TermForwardSimulator.bulk_test_if_paths_are_sufficient``). It would be difficult to reproduce current behavior exactly, since the call to ``bulk_test_if_paths_are_sufficient`` requires the value of ``self.probs`` before we account for "omitted probs" and regularization.
2. We're now performing a check that terms is nonnegative, while we were performing no such check in the past. If we don't want to add this check then I can remove it and just change the docstring accordingly. I'd also want to change lsvec to raise a warning if oob_check was anything other than False in this case (since ``oob_check=True`` wouldn't be used for anything).

2024-12-18 13:09 UTC, rileyjmurray commented
During the 12/17 dev meeting Erik raised the question of how numerics might be different by focusing on "terms" and computing "lsvec" as a function of terms. This comment (which will be edited ...) documents my investigation on this front.

2025-01-17 17:48 UTC, sserita requested changes
Thanks for the huge effort @rileyjmurray, and the very detailed post explaining the differences. That helped a lot.
I tried to have maximal mercy but I couldn't stop myself from having two minor comment-related requests - add those in and it'll be a quick approve from me.

2025-01-17 18:29 UTC, rileyjmurray commented on pygsti/objectivefns/objectivefns.py
> +        out = (probs - freqs) * self._weights(probs, freqs, total_counts)  # Note: ok if this is negative
It just makes debugging easier. This way I'm able to set a breakpoint in a stack frame that only has the variables relevant to this function, _and_ I can see what this function returns. (Compare to the direct return, which would give me the variables in the stack frame but not allow me to inspect the output.)

2025-01-17 18:29 UTC, rileyjmurray commented on test/unit/mpi/test_mpi.py
> +except (ImportError, RuntimeError):
I gotchu

2025-01-17 18:30 UTC, rileyjmurray commented on test/test_packages/drivers/test_calcmethods1Q.py
> +        target_model.from_vector(1e-9 * np.ones(target_model.num_params))  # to seed term calc (starting with perfect zeros causes trouble)
Uhhh .... if I didn't make it, then the test failed nastily.

I can compare side by side and see what the threshold is for the old code vs new code.

2025-01-17 18:31 UTC, rileyjmurray commented on pygsti/objectivefns/objectivefns.py
> +            paramvec_norm = self.regularize_factor * _np.array([max(0, absx - 1.0) for absx in map(abs, paramvec)], 'd')
Super reasonable!

2025-01-17 22:00 UTC, rileyjmurray commented on test/test_packages/drivers/test_calcmethods1Q.py
> +        target_model.from_vector(1e-9 * np.ones(target_model.num_params))  # to seed term calc (starting with perfect zeros causes trouble)
@sserita, I'm very glad you asked this question. It turns out that the non-convergence I observed stemmed from a bug in the LM optimizer. Specifically, it stemmed from how the LM optimizer decided to update the "best_x."

The implementations on develop (i.e., both the default SimplerLMOptimizer and the backup CustomLMOptimizer) would only update ``best_x`` if ``norm_f < min_norm_f`` _and_ a boolean flag called ``new_x_is_known_in_bounds`` was True. But ``new_x_is_known_in_bounds`` is really more of a sufficient condition for being in bounds than a necessary condition. It makes more sense to do this:
> If ``norm_f < min_norm_f``, then check if ``new_x_is_known_in_bounds == True``. If it is, then we take this flag's word for it and update ``best_x[:] = x``. Otherwise, we explicitly check if ``x`` is in bounds and we update ``best_x[:] = x`` if and only if that's the case.

If I make that change then the test passes without making the change that prompted your comment.

See below for my investigation, written to a future pyGSTi developer who might come across this.

## Investigation

Stefan's comment concerned a change I made in  ``test/test_packages/drivers/test_calcmethods1Q.py::test_stdgst_prunedpath``. The change was to replace a scalar that was hard-coded to 1e-10 with a scalar hard-coded to 1e-9. Let's call that scalar ``perturb``. So the old value is ``perturb=1e-10``.

I ran this test on develop with different values of ``perturb``; those runs passed when ``perturb >= 5e-13`` and failed when ``perturb <= 2.5e-13``. Then I ran this test on the current branch using the commit at the time that Stefan left his comment. Those runs passed when ``perturb >= 2e-10`` and failed when ``perturb <= 1.125``.

I started to write a report of these observations when I noticed something funny. In the test log it was clear that the LM optimizer was terminating outer iterations with a _much_ larger value for ``norm_f`` than the minimum value seen across the outer iterations (specific logs are shown below). This made me suspect that ``best_x`` wasn't being set properly. Sure enough, I found this issue where a _sufficient condition_ for an iterate being in-bounds (``new_x_is_known_in_bounds``) was effectively used as a necessary condition. After updating the termination criteria I was able to get this problematic unit test to pass when ``perturb==1e-10``. In fact, it passed with ``perturb==1e-12``. I didn't bother checking smaller values.

### develop, passing with 5e-13
```
  Last iteration:
  --- dlogl GST ---
  Initial Term-stage model has 0 failures and uses 10.0% of allowed paths (ok=True).
    --- Outer Iter 0: norm_f = 166109, mu=1, |x|=2.44949e-12, |J|=2835.48
    --- Outer Iter 1: norm_f = 166104, mu=979.996, |x|=0.00324549, |J|=2835.51
    --- Outer Iter 2: norm_f = 608.149, mu=326.665, |x|=0.255707, |J|=3040.87
    --- Outer Iter 3: norm_f = 95.8116, mu=168.158, |x|=0.276211, |J|=3017.42
    --- Outer Iter 4: norm_f = 31.8847, mu=56.0528, |x|=0.268233, |J|=3017.41
    --- Outer Iter 5: norm_f = 31.864, mu=18.6843, |x|=0.268133, |J|=3017.33
    --- Outer Iter 6: norm_f = 166104, mu=979.996, |x|=0.00324549, |J|=3017.33
Paths are insufficient! (Using meanscaled heuristic with error bound of 0.1)
    Least squares message = Objective function out-of-bounds! STOP
  2*Delta(log(L)) = 332207 (66 data params - 24 (approx) model params = expected mean of 42; p-value = 0)
Pruned path-integral: kept 13212 paths (10.0%) w/magnitude 135.6 (target=134.4, #circuits=66, #failed=0)
  (avg per circuit paths=200, magnitude=2.055, target=2.036)
  After adapting paths, num failures = 0, 10.0% of allowed paths used.
    --- Outer Iter 0: norm_f = 166104, mu=979.996, |x|=0.00324549, |J|=2835.51
    --- Outer Iter 1: norm_f = 608.149, mu=326.665, |x|=0.255707, |J|=3040.87
    --- Outer Iter 2: norm_f = 95.8116, mu=168.158, |x|=0.276211, |J|=3017.42
    --- Outer Iter 3: norm_f = 31.8847, mu=56.0528, |x|=0.268233, |J|=3017.41
    --- Outer Iter 4: norm_f = 31.864, mu=18.6843, |x|=0.268133, |J|=3017.33
    --- Outer Iter 5: norm_f = 608.149, mu=326.665, |x|=0.255707, |J|=3017.33
    --- Outer Iter 6: norm_f = 607.403, mu=1.52598e+07, |x|=0.255282, |J|=3040.98
    --- Outer Iter 7: norm_f = 591.59, mu=5.08659e+06, |x|=0.255303, |J|=3040.85
    --- Outer Iter 8: norm_f = 548.357, mu=1.69553e+06, |x|=0.255395, |J|=3040.46
    --- Outer Iter 9: norm_f = 448.118, mu=565177, |x|=0.255827, |J|=3039.43
    --- Outer Iter 10: norm_f = 289.143, mu=188392, |x|=0.257372, |J|=3037.08
    --- Outer Iter 11: norm_f = 150.619, mu=62797.4, |x|=0.260537, |J|=3032.8
    --- Outer Iter 12: norm_f = 68.2405, mu=20932.5, |x|=0.26454, |J|=3026.4
    --- Outer Iter 13: norm_f = 36.1194, mu=6977.49, |x|=0.267382, |J|=3020.41
    --- Outer Iter 14: norm_f = 31.9729, mu=2325.83, |x|=0.268035, |J|=3017.84
    --- Outer Iter 15: norm_f = 31.8644, mu=775.277, |x|=0.268122, |J|=3017.37
    --- Outer Iter 16: norm_f = 31.864, mu=258.426, |x|=0.268135, |J|=3017.33
    Least squares message = Both actual and predicted relative reductions in the sum of squares are at most 1e-06
  2*Delta(log(L)) = 63.7279 (66 data params - 24 (approx) model params = expected mean of 42; p-value = 0.0168613)
  Term-states Converged!
  Completed in 0.7s
  Final optimization took 0.7s
```
### develop, passing with 2e-10
```
  Last iteration:
  --- dlogl GST ---
  Initial Term-stage model has 0 failures and uses 10.0% of allowed paths (ok=True).
    --- Outer Iter 0: norm_f = 166109, mu=1, |x|=9.79796e-10, |J|=2835.48
    --- Outer Iter 1: norm_f = 166090, mu=979.996, |x|=0.00324842, |J|=2851.83
    --- Outer Iter 2: norm_f = 26560.4, mu=334505, |x|=0.094016, |J|=3265.36
    --- Outer Iter 3: norm_f = 3024.04, mu=117205, |x|=0.198562, |J|=3065.56
    --- Outer Iter 4: norm_f = 223.51, mu=39068.3, |x|=0.250841, |J|=3037.55
    --- Outer Iter 5: norm_f = 61.1352, mu=13022.8, |x|=0.264528, |J|=3026.48
    --- Outer Iter 6: norm_f = 34.14, mu=4340.92, |x|=0.267594, |J|=3019.84
    --- Outer Iter 7: norm_f = 31.9082, mu=1446.97, |x|=0.268025, |J|=3017.7
    --- Outer Iter 8: norm_f = 31.8645, mu=482.324, |x|=0.26812, |J|=3017.36
    --- Outer Iter 9: norm_f = 31.864, mu=160.775, |x|=0.268135, |J|=3017.33
    --- Outer Iter 10: norm_f = 166090, mu=979.996, |x|=0.00324842, |J|=3017.33
Paths are insufficient! (Using meanscaled heuristic with error bound of 0.1)
    Least squares message = Objective function out-of-bounds! STOP
  2*Delta(log(L)) = 332181 (66 data params - 24 (approx) model params = expected mean of 42; p-value = 0)
Pruned path-integral: kept 13212 paths (10.0%) w/magnitude 135.6 (target=134.4, #circuits=66, #failed=0)
  (avg per circuit paths=200, magnitude=2.055, target=2.036)
  After adapting paths, num failures = 0, 10.0% of allowed paths used.
    --- Outer Iter 0: norm_f = 166090, mu=979.996, |x|=0.00324842, |J|=2851.83
Paths are insufficient! (Using meanscaled heuristic with error bound of 0.1)
Paths are insufficient! (Using meanscaled heuristic with error bound of 0.1)
Paths are insufficient! (Using meanscaled heuristic with error bound of 0.1)
Paths are insufficient! (Using meanscaled heuristic with error bound of 0.1)
    --- Outer Iter 1: norm_f = 26560.4, mu=334505, |x|=0.094016, |J|=3265.36
    --- Outer Iter 2: norm_f = 3024.04, mu=117205, |x|=0.198562, |J|=3065.56
    --- Outer Iter 3: norm_f = 223.51, mu=39068.3, |x|=0.250841, |J|=3037.55
    --- Outer Iter 4: norm_f = 61.1352, mu=13022.8, |x|=0.264528, |J|=3026.48
    --- Outer Iter 5: norm_f = 34.14, mu=4340.92, |x|=0.267594, |J|=3019.84
    --- Outer Iter 6: norm_f = 31.9082, mu=1446.97, |x|=0.268025, |J|=3017.7
    --- Outer Iter 7: norm_f = 31.8645, mu=482.324, |x|=0.26812, |J|=3017.36
    --- Outer Iter 8: norm_f = 31.864, mu=160.775, |x|=0.268135, |J|=3017.33
    --- Outer Iter 9: norm_f = 26560.4, mu=334505, |x|=0.094016, |J|=3017.33
    --- Outer Iter 10: norm_f = 24207.2, mu=111502, |x|=0.0993976, |J|=3245.77
    --- Outer Iter 11: norm_f = 1743.06, m [...]

2025-01-17 22:04 UTC, coreyostrove commented on test/test_packages/drivers/test_calcmethods1Q.py
> +        target_model.from_vector(1e-9 * np.ones(target_model.num_params))  # to seed term calc (starting with perfect zeros causes trouble)
Fantastic work tracking this down, @rileyjmurray!

2025-01-17 22:08 UTC, rileyjmurray commented on test/test_packages/drivers/test_calcmethods1Q.py
> +        target_model.from_vector(1e-9 * np.ones(target_model.num_params))  # to seed term calc (starting with perfect zeros causes trouble)
Thanks, @coreyostrove! I feel pretty good about this one. Who knows how many past calls to LM suffered from this bug. It's wild to think about, since LM was _already_ performing very well, and now it'll perform even better :)

2025-01-17 22:15 UTC, rileyjmurray commented
@sserita once tests pass we should be good to merge :)

2025-01-20 22:47 UTC, sserita approved these changes
Thanks as always for the great work, and tracking down that bug in the LM code!

2025-01-20 22:47 UTC, merged

2025-01-20 22:48 UTC, sserita commented on test/test_packages/drivers/test_calcmethods1Q.py
> +        target_model.from_vector(1e-9 * np.ones(target_model.num_params))  # to seed term calc (starting with perfect zeros causes trouble)
Agreed, nice work and as always, the detailed writeups are incredibly appreciated!